# Generated by Django 6.0.6 on 2026-07-17 17:56

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0002_alter_invitation_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('action_type', models.CharField(choices=[('member_invited', 'Member Invited'), ('member_removed', 'Member Removed'), ('role_changed', 'Role Changed'), ('org_settings_changed', 'Org Settings Changed'), ('ownership_transferred', 'Ownership Transferred'), ('hard_deleted', 'Hard Deleted'), ('restored', 'Restored')], max_length=40)),
                ('target_object_id', models.BigIntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('actor_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='idx_audit_logs_org_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action_type__in', ['member_invited', 'member_removed', 'role_changed', 'org_settings_changed', 'ownership_transferred', 'hard_deleted', 'restored'])), name='audit_logs_action_type_valid')],
            },
        ),
    ]
