# Generated by Django 6.0.6 on 2026-07-24 11:34

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0002_alter_invitation_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('follow_up', 'Follow-up'), ('task', 'Task'), ('reminder', 'Reminder')], max_length=20)),
                ('parent_object_id', models.BigIntegerField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_activities', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('parent_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'activities',
                'indexes': [models.Index(fields=['parent_content_type', 'parent_object_id'], name='idx_activities_parent'), models.Index(fields=['assignee', 'due_date'], name='idx_activities_assignee_due')],
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['call', 'meeting', 'follow_up', 'task', 'reminder'])), name='activities_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'completed', 'cancelled'])), name='activities_status_valid')],
            },
        ),
    ]
