name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat > .env <<EOF
          DJANGO_SETTINGS_MODULE=config.settings.test
      
          SECRET_KEY=test-secret-key
      
          DEBUG=False
      
          POSTGRES_DB=test_db
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
      
          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          EOF

      - name: Build
        run: docker build -f docker/Dockerfile -t crm-backend .

      - name: Show compose logs
        if: failure()
        run: |
          docker compose --env-file .env -f docker/docker-compose.yml logs

      - name: Start containers
        run: docker compose --env-file .env -f docker/docker-compose.yml up -d

      - name: Wait
        run: sleep 15

      - name: Show containers
        if: always()
        run: docker compose --env-file .env -f docker/docker-compose.yml ps

      - name: Show web logs
        if: failure()
        run: docker compose --env-file .env -f docker/docker-compose.yml logs web

      - name: Migrate
        run: docker compose --env-file .env -f docker/docker-compose.yml exec -T web python manage.py migrate

      - name: Run Tests
        run: docker compose --env-file .env -f docker/docker-compose.yml exec -T web python manage.py test

      - name: Ruff
        run: docker compose --env-file .env -f docker/docker-compose.yml exec -T web ruff check .

      - name: Black
        run: docker compose --env-file .env -f docker/docker-compose.yml exec -T web black --check .

      - name: Stop
        if: always()
        run: docker compose -f docker/docker-compose.yml down -v
